// Generated by ts-to-zod
import { z } from "zod";

export const mediaUrlSchema = z.object({
  src: z.string(),
  mimeType: z.string().optional(),
  description: z.string().optional(),
});

export const enumWrapperSchema = z.object({
  name: z.string(),
  variant: z.string(),
  value: z.string(),
});

export const translationSchema = z.object({
  lang: z.string(),
  value: z.string(),
});

export const pronunciationSchema = z.object({
  kind: enumWrapperSchema.optional(),
  value: z.string(),
  media: z.array(mediaUrlSchema),
});

export const exampleSchema = z.object({
  value: z.string(),
  translations: z.array(translationSchema),
  pronunciations: z.array(pronunciationSchema),
});

export const remoteLoadOptionsSchema = z.object({
  outDir: z.string().optional(),
  caching: z.boolean().optional(),
  retries: z.number().optional(),
});

export const compressOptionsSchema = z.object({
  quality: z.number().optional(),
  windowSize: z.number().optional(),
});

export const lookupOptionsSchema = z.object({
  split: z.number().optional(),
  follow: z.boolean().optional(),
  insensitive: z.boolean().optional(),
});

export const indexOptionsSchema = z.object({
  directory: z.string().optional(),
  memory: z.number().optional(),
  overwrite: z.boolean().optional(),
});

export const searchOptionsSchema = z.object({
  directory: z.string().optional(),
  threshold: z.number().optional(),
  autoindex: z.boolean().optional(),
  limit: z.number().optional(),
});

export const tokenizeOptionsSchema = z.object({
  follow: z.boolean().optional(),
  allowList: z.array(z.string()).optional(),
  insensitive: z.boolean().optional(),
});

export const noteSchema = z.object({
  id: z.string().optional(),
  value: z.string(),
  examples: z.array(exampleSchema),
});

export const definitionSchema = z.object({
  id: z.string().optional(),
  value: z.string(),
  examples: z.array(exampleSchema),
  notes: z.array(noteSchema),
});

export const loadOptionsSchema = z.object({
  configDir: z.string().optional(),
  remote: remoteLoadOptionsSchema.optional(),
});

export const saveOptionsSchema = z.object({
  compress: compressOptionsSchema.optional(),
});

export const groupSchema = z.object({
  id: z.string().optional(),
  description: z.string(),
  definitions: z.array(definitionSchema),
});
